# X-VLM-base pretrained by 4M images, initialized with BERT-base & Swin-base

## Data
train_file: [
    "hdfs://path/to/coco",  # a directory, which contains for example 64 files. Each file contains multiple lines, and each line is a json object(dict).
    "hdfs://path/to/vg",
    "hdfs://path/to/sbu",
    "hdfs://path/to/cc3m",
               ]  # local files are also ok

train_dataset_size: 5114489 # for IterableDataset
images: {image_key: "binary",
         is_image_rpath: False, # read path or base64 encoding (if reading from HDFS)
         caption_key: "caption",
         tokenized: False,  # whether texts have been tokenized
         batch_size: 128,  # 128 x 8 = 1024
         num_workers: 4,  # better -> the total number of training files % (world_size * num_workers) == 0
}


train_file_regions: [
    'hdfs://path/to/coco_objs',
    'hdfs://path/to/vg_objs',
    'hdfs://path/to/vg_regions',
]
regions: {image_key: "binary", is_image_rpath: False, caption_key: "caption", tokenized: False,
          iter_perc: 0.5, batch_size: 128, max_images: 48, max_regions: 5, min_perc_in_image: 0.5, num_workers: 4}


## Vision Encoder

use_clip_vit: False
#vision_config: 'configs/config_clipvitB.json'
#image_res: 224
#patch_size: 16


use_swin: True
vision_config: 'configs/config_swinB_224.json'
image_res: 224
patch_size: 32


## Text Encoder
use_roberta: False
text_config: 'configs/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: 'data/bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']

load_bertL_by_sep: False # loading parameters 12+12L -> 12+6L, for X-VLM-large


## Training
calc_image_bbox_loss: False
embed_dim: 256
temp: 0.07

max_words: 40  # i use 30 for 14M
max_tokens: 40
mask_prob: 0.25
max_masks: 8
mask_whole_word: True
skipgram_prb: 0.2
skipgram_size: 3


## Other Settings
ckpt_frequent_step: 50000
ckpt_frequent: 5  # epoch
optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 1e-4, epochs: 41, num_warmup_steps: 2500}
accelerator: {SYNCBN: false, FP16_OPT_LEVEL: O1, FP16_LOSS_SCALE: dynamic, RNG_SEED: 42, GRAD_ACCUMULATE_STEPS: 1, CLIP_GRAD_NORM: 1.0}







